### ISSUE TITLE
Just a hello

### ISSUE THREAD

**Issue by richyvk** [ICLRandD/Blackstone#11]
Hi (Dan),

Just a hello, to say met with Paul & Paul on Friday. They gave us here at SCLQ a great chance to discuss all the cool stuff you've got going on. I am going to start playing with Blackstone and getting it to look at some of our Qld decisions.

One thing I'd like to discuss at some point is how to train it. Perhaps we can Skype sometime?

**Comment by richyvk** [comment]
Hi again. Trying to get Blackstone installed on my Macbook. I have Python 3.7.5 running in a venv. Have installed both Blackstone and the model (en-blackstone-proto 0.0.1) as per your README. 
When I try and run your "Applying the NER model" example I get an error:

```Traceback (most recent call last):
  File "blackstone_test.py", line 10, in <module>
    doc = nlp(text)
  File "/Users/admin/Documents/Blackstone/blackstone/lib/python3.7/site-packages/spacy/language.py", line 435, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "pipes.pyx", line 396, in spacy.pipeline.pipes.Tagger.__call__
  File "pipes.pyx", line 441, in spacy.pipeline.pipes.Tagger.set_annotations
  File "morphology.pyx", line 312, in spacy.morphology.Morphology.assign_tag_id
  File "morphology.pyx", line 200, in spacy.morphology.Morphology.add
ValueError: [E167] Unknown morphological feature: 'ConjType' (9141427322507498425). This can happen if the tagger was trained with a different set of morphological features. If you're using a pretrained model, make sure that your models are up to date:
python -m spacy validate
(blackstone) Admins-MacBook-Pro:Blackstone admin$ python -m spacy validate
✔ Loaded compatibility table

====================== Installed models (spaCy v2.2.2) ======================
ℹ spaCy installation:
/Users/admin/Documents/Blackstone/blackstone/lib/python3.7/site-packages/spacy

No models found in your current environment.
```
Not sure if this a red herring but I noticed running `python -m spacy validate`, as the error suggested, mentions that No models found. But when I run pip list I can clearly see the model is installed.

Any ideas how to get this sorted?

It fails on the line doc = nlp(text) so it seems like the model imports OK??

**Comment by richyvk** [comment]
Hi again. Figured it out. Doesn't like spacy 2.2.*, rolled back to 2.1.8 and all good :)
